<#
.SYNOPSIS
    AutoTask Snapshot Tool V2.11
    用於打包所有腳本、設定檔與最近日誌，供 AI 進行除錯分析。
    V2.11: 修正 BetterGI 日誌擷取路徑為 "C:\Program Files\BetterGI\log"。
#>

$SnapshotVersion = "V2.11"
$SourceDir = "C:\AutoTask"
$OutputDir = "C:\AutoTask_Snapshots"
$Timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$ZipName = "AutoTask_Snapshot_$Timestamp.zip"
$ZipPath = Join-Path $OutputDir $ZipName

# 核心分析文件路徑
$CoreDocPath = "$SourceDir\Scripts\AutoTask_Core_Analysis.md"
if (-not (Test-Path $CoreDocPath)) { $CoreDocPath = "$SourceDir\AutoTask_Core_Analysis.md" }

$TempDir = Join-Path $OutputDir "Temp_$Timestamp"
$TempSource = Join-Path $TempDir "1_Source_Code"
$TempConfigs = Join-Path $TempDir "2_Configs"
$TempLogs = Join-Path $TempDir "3_Logs_Summary"

New-Item -ItemType Directory -Path $TempSource -Force | Out-Null
New-Item -ItemType Directory -Path $TempConfigs -Force | Out-Null
New-Item -ItemType Directory -Path $TempLogs -Force | Out-Null

Write-Host "=== AutoTask Snapshot Tool $SnapshotVersion ===" -ForegroundColor Cyan
Write-Host "正在準備快照包..."

# ==============================================================================
# 1. 原始碼合併
# ==============================================================================
Write-Host " -> 1/4 正在合併原始碼..."
$CombinedSourceFile = Join-Path $TempSource "All_Source_Combined.txt"
$SourceHeader = "=== [ AutoTask Full Source Code Dump ] ===`r`nGenerated by Task_Snapshot $SnapshotVersion`r`n`r`n"
Set-Content -Path $CombinedSourceFile -Value $SourceHeader -Encoding UTF8

if (Test-Path $CoreDocPath) {
    $DocBlock = "`r`n######################################################################`r`nFILE: AutoTask_Core_Analysis.md`r`nTYPE: Core Logic Documentation`r`n######################################################################`r`n`r`n"
    Add-Content -Path $CombinedSourceFile -Value $DocBlock -Encoding UTF8
    Add-Content -Path $CombinedSourceFile -Value (Get-Content $CoreDocPath -Raw) -Encoding UTF8
}

$SourceFiles = @()
$SourceFiles += Get-ChildItem -Path $SourceDir -Filter "*.bat" -File
$SourceFiles += Get-ChildItem -Path "$SourceDir\Scripts" -Filter "*.ps1" -File

foreach ($File in $SourceFiles) {
    if ($File.FullName -eq $CoreDocPath) { continue }
    $FileBlock = "`r`n######################################################################`r`nFILE: $($File.Name)`r`nPATH: $($File.FullName)`r`n######################################################################`r`n`r`n"
    Add-Content -Path $CombinedSourceFile -Value $FileBlock -Encoding UTF8
    if (Test-Path $File.FullName) { Add-Content -Path $CombinedSourceFile -Value (Get-Content $File.FullName -Raw) -Encoding UTF8 }
}

# ==============================================================================
# 2. 設定檔合併
# ==============================================================================
Write-Host " -> 2/4 正在合併設定檔..."
$CombinedConfigFile = Join-Path $TempConfigs "All_Configs_Combined.txt"
Set-Content -Path $CombinedConfigFile -Value "=== [ AutoTask Configs ] ===`r`n" -Encoding UTF8

$ConfigFiles = Get-ChildItem -Path "$SourceDir\Configs" -File
foreach ($File in $ConfigFiles) {
    $FileBlock = "`r`n######################################################################`r`nFILE: $($File.Name)`r`n######################################################################`r`n`r`n"
    Add-Content -Path $CombinedConfigFile -Value $FileBlock -Encoding UTF8
    if (Test-Path $File.FullName) { Add-Content -Path $CombinedConfigFile -Value (Get-Content $File.FullName -Raw) -Encoding UTF8 }
}

# 匯出排程器 XML
$TasksToExport = @("Auto_1Remote_Master", "Auto_BetterGI_Payload")
foreach ($TaskName in $TasksToExport) {
    try {
        $TempXmlPath = Join-Path $TempDir "$TaskName.xml"
        Export-ScheduledTask -TaskName $TaskName | Out-File -FilePath $TempXmlPath -Encoding UTF8
        $FileBlock = "`r`n######################################################################`r`nFILE: $TaskName.xml`r`n######################################################################`r`n`r`n"
        Add-Content -Path $CombinedConfigFile -Value $FileBlock -Encoding UTF8
        Add-Content -Path $CombinedConfigFile -Value (Get-Content $TempXmlPath -Raw) -Encoding UTF8
        Remove-Item -Path $TempXmlPath -Force
    } catch {}
}

# ==============================================================================
# 3. 日誌摘要
# ==============================================================================
Write-Host " -> 3/4 正在生成日誌摘要..."

function Get-SmartLogContent {
    param ( [string]$FilePath )
    $FileInfo = Get-Item $FilePath
    if ($FileInfo.Length -gt 2MB) {
        $Content = Get-Content -Path $FilePath -Tail 5000 -Raw
        if ($Content.Length -gt 2MB) { $Content = $Content.Substring($Content.Length - 2MB) }
        return "[TRUNCATED] ...`r`n`r`n" + $Content
    } else {
        return Get-Content -Path $FilePath -Raw
    }
}

$LogsDir = "$SourceDir\Logs"
$RemoteLogsDir = "$SourceDir\1Remote\Log"
# [V2.11 Fix] 更新 BetterGI 日誌路徑為 "log"
$BetterGILogsDir = "C:\Program Files\BetterGI\log"

$LogsOutFile = Join-Path $TempLogs "Recent_Logs_Summary.txt"
Set-Content -Path $LogsOutFile -Value "=== [ Recent Logs Summary ] ===`r`n" -Encoding UTF8

$LogTargets = @()
if (Test-Path $LogsDir) { $LogTargets += Get-ChildItem -Path $LogsDir -Filter "*.log" | Sort LastWriteTime -Desc | Select -First 2 }
if (Test-Path $RemoteLogsDir) { $LogTargets += Get-ChildItem -Path $RemoteLogsDir -Filter "*.md" | Sort LastWriteTime -Desc | Select -First 2 }
if (Test-Path $BetterGILogsDir) { $LogTargets += Get-ChildItem -Path $BetterGILogsDir -Filter "*.log" | Sort LastWriteTime -Desc | Select -First 2 }

foreach ($File in $LogTargets) {
    if ($null -eq $File) { continue }
    $Header = "`r`n======================================================================`r`nFILE: $($File.Name)`r`nPATH: $($File.FullName)`r`nSIZE: $([math]::Round($File.Length / 1MB, 2)) MB`r`n======================================================================`r`n"
    Add-Content -Path $LogsOutFile -Value $Header -Encoding UTF8
    $Content = Get-SmartLogContent -FilePath $File.FullName
    $Content | Out-File -FilePath $LogsOutFile -Append -Encoding UTF8
}

# ==============================================================================
# 4. 壓縮
# ==============================================================================
Write-Host " -> 4/4 正在壓縮打包..."
Compress-Archive -Path "$TempDir\*" -DestinationPath $ZipPath -Force
Remove-Item -Path $TempDir -Recurse -Force
Write-Host "`r`n[完成] 快照已儲存至: $ZipPath" -ForegroundColor Green
Start-Process "explorer.exe" -ArgumentList "/select,`"$ZipPath`""